language: php
php:
  - '5.6'
  - '7.3'
  - '7.4'
  - '8.0'
  - nightly
sudo: required
dist: trusty
services:
  - postgresql
env:
  - POSTGRESQL_VERSION=9.6
  - POSTGRESQL_VERSION=10
  - POSTGRESQL_VERSION=11
  - POSTGRESQL_VERSION=12
  - POSTGRESQL_VERSION=13
before_script:
  - composer install
  - sudo service postgresql stop; sudo service postgresql start $POSTGRESQL_VERSION
  - psql -c 'create database migrations_test;' -U postgres
script: vendor/bin/phpunit tests
