language: php
php:
  - '5.6'
  - '7.0'
  - nightly
sudo: required
dist: trusty
services:
  - postgresql
env:
  - POSTGRESQL_VERSION=9.1
  - POSTGRESQL_VERSION=9.2
  - POSTGRESQL_VERSION=9.3
  - POSTGRESQL_VERSION=9.4
  - POSTGRESQL_VERSION=9.5
before_script:
  - composer install
  - sudo service postgresql stop; sudo service postgresql start $POSTGRESQL_VERSION
  - psql -c 'create database migrations_test;' -U postgres
script: vendor/bin/phpunit tests
